# fly.toml app configuration file generated for the-andy-book-app on 2023-05-03T09:04:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "the-andy-book-app"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
